version: '3'

services:
  app:
    image: chatgptweb/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3004:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # choose one
      OPENAI_API_KEY:
      # API interface address, optional, available when OPENAI_API_KEY is set
      OPENAI_API_BASE_URL: https://api.chatanywhere.com.cn
      # API model, optional, available when OPENAI_API_KEY is set, https://platform.openai.com/docs/models
      # gpt-4, gpt-4-turbo-preview, gpt-4-0125-preview, gpt-4-1106-preview, gpt-4-0314, gpt-4-0613, gpt-4-32k, gpt-4-32k-0314, gpt-4-32k-0613, gpt-3.5-turbo-16k, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo, gpt-3.5-turbo-0301, gpt-3.5-turbo-0613, text-davinci-003, text-davinci-002, code-davinci-002
      OPENAI_API_MODEL: gpt-3.5-turbo-1106
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: RvBNAFc6iRZT0x4bPkzVUorBnwUxh4rONi6T4eMD1SP33miO-8gws33A-LNu5dwAA
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 网站名称
      SITE_TITLE: ChatGpt Web
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:3SONqroYBCPKmi2j@database:27018'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: ZT0x4bPkzVUorBnwUxh4rONi6T4e
      # 开启注册之后 超级管理邮箱
      ROOT_USER: wangmoonsoh@gmail.com
      # 网站是否开启注册 必须开启, 否则管理员都没法注册, 可后续关闭
      REGISTER_ENABLED: true
      # 更多配置, 在运行后, 注册管理员, 在管理员页面中设置
    links:
      - database

  database:
    image: mongo
    ports:
      - '27018:27017'
    expose:
      - '27018'
    volumes:
      - /usr/local/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: 3SONqroYBCPKmi2j
      MONGO_INITDB_DATABASE: chatgpt

volumes:
  mongodb: {}
